title: ishkawa
email: y@ishkawa.org
description: ""
baseurl: ""
url: "https://blog.ishkawa.org"
timezone: Asia/Tokyo
twitter_username: _ishkawa
github_username:  ishkawa

permalink: pretty

plugins:
  - jekyll-feed

feed:
  path: atom.xml
